services:
    postgres:
        image: 'postgres:16'
        ports:
            - '127.0.0.1:5432:5432'
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "luckation" ]
            interval: 5s
            timeout: 5s
            retries: 6
        environment:
            POSTGRES_DB: 'luckation'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            TZ: 'Europe/Moscow'
        volumes:
            - 'postgres:/var/lib/postgresql/data'
volumes:
    postgres: