services:
  mainmodule:
    build:
      context: .
      dockerfile: MainModule/Dockerfile
    volumes:
      - ./MainModule:/code
    ports:
      - 5000:80

  bot:
    build:
      context: ./TextBot
      dockerfile: Dockerfile
    ports:
      - 5001:80
    env_file:
      - .env
    volumes:
      - ./TextBot/support.session:/code/app/support.session

  sound:
    build:
      context: ./Sound
      dockerfile: Dockerfile
    ports:
      - 5002:80
