"""

Revision ID: b747b04c5452
Revises: a407c34fb99b
Create Date: 2024-09-07 19:44:14.298619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b747b04c5452'
down_revision: Union[str, None] = 'a407c34fb99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
